apiVersion: batch/v1
kind: Job
metadata:
  name: test-scratch
spec:
  template:
    spec:
      priorityClassName: research-med
      containers:
        - name: custom-container-name
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/extgruenlab3/base_kallisto
          imagePullPolicy: "Always"
          env:
            - name: kallisto
              value: "hello"
            - name: bustools # example usage of env variable
              value: "/mydir"
          resources:
            limits:
              cpu: "4"
              memory: "64Gi"
            requests:
              cpu: "4"
              memory: "64Gi"
          command: ["/home/ext/agrawal/FastqFiles/map_transcriptome.sh"]
          volumeMounts:
            - mountPath: /home/ext/agrawal/
              name: localdir  
            - mountPath: /scratch/gruenlab/repository/
              name: scratchdir    
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: localdir
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: extagrawal  # <namespace>
            path: "/home/ext/agrawal/" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret
        - cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  
            user: extagrawal  
            path: /scratch/gruenlab/repository/
            secretRef: 
              name: ceph-secret
          name: scratchdir
              

